### ISSUE TITLE
Process `NFCORE_CHIPSEQ:PREPARE_GENOME:GFFREAD` declares 2 input channels but 1 were specified

### ISSUE THREAD

**Issue by ftabaro** [nf-core/ChIPseq#432]
### Description of the bug

Hello everybody, when running this pipeline with GFF annotation as input it throws the following error:

```
Process `NFCORE_CHIPSEQ:PREPARE_GENOME:GFFREAD` declares 2 input channels but 1 were specified
```

I am using the data from nf-core/test and pipeline configuration very similar to the test one. Here are my parameters:

```yaml
input: samplesheet_test.csv
outdir: results
fasta: genome.fa
gff: genes.gff
read_length: 50
narrow_peak: true
skip_preseq: true
```

I am attaching an archive to reproduce the error.

### Command used and terminal output

```console
nextflow run nf-core/chipseq -r 2.1.0 -profile conda -params-file params.yml
```

### Relevant files

[gff-bug.zip](https://github.com/user-attachments/files/17818503/gff-bug.zip)

### System information

-  Nextflow version: 24.10.0
-  Hardware: HPC and desktop
-  Executor: singularity and conda
-  Container engine: Singularity/Apptainer
-  OS: Fedora 41 and RHEL 8
-  Version of nf-core/chipseq: 2.1.0
